"""
REST API routes for water heater operations with configurable data sources.
"""
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel, Field

from src.models.water_heater import (
    WaterHeater, 
    WaterHeaterMode,
    WaterHeaterStatus, 
    WaterHeaterReading
)
from src.services.configurable_water_heater_service import ConfigurableWaterHeaterService

router = APIRouter(tags=["water_heaters"])

# Request Models
class CreateWaterHeaterRequest(BaseModel):
    """Request model for creating a water heater."""
    name: str
    model: Optional[str] = None
    manufacturer: Optional[str] = None
    target_temperature: Optional[float] = None
    current_temperature: Optional[float] = None
    status: Optional[str] = None
    mode: Optional[str] = None
    health_status: Optional[str] = "GREEN"

class TemperatureUpdateRequest(BaseModel):
    """Request model for updating target temperature."""
    temperature: float = Field(..., ge=30.0, le=80.0, description="Target temperature in Celsius (30-80°C)")

class ModeUpdateRequest(BaseModel):
    """Request model for updating operational mode."""
    mode: WaterHeaterMode

class ReadingAddRequest(BaseModel):
    """Request model for adding a sensor reading."""
    temperature: float = Field(..., description="Current temperature reading in Celsius")
    pressure: Optional[float] = Field(None, description="Current pressure reading in bar")
    energy_usage: Optional[float] = Field(None, description="Current energy usage in watts")
    flow_rate: Optional[float] = Field(None, description="Current flow rate in liters per minute")

class AlertRuleRequest(BaseModel):
    """Request model for water heater alert rules."""
    name: str = Field(..., description="Alert rule name")
    condition: str = Field(..., description="Alert condition expression")
    severity: str = Field(..., description="Alert severity level")
    message: Optional[str] = Field(None, description="Alert message")
    enabled: bool = Field(True, description="Whether the alert is enabled")

# Get service instance
def get_service() -> ConfigurableWaterHeaterService:
    """Get an instance of the configurable water heater service."""
    return ConfigurableWaterHeaterService()

# Routes
@router.get("/water-heaters", response_model=List[WaterHeater])
async def get_water_heaters(service: ConfigurableWaterHeaterService = Depends(get_service)):
    """
    Get all water heaters.
    """
    return await service.get_water_heaters()

@router.get("/water-heaters/{device_id}", response_model=WaterHeater)
async def get_water_heater(device_id: str, service: ConfigurableWaterHeaterService = Depends(get_service)):
    """
    Get a specific water heater by ID.
    """
    water_heater = await service.get_water_heater(device_id)
    if not water_heater:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    return water_heater

@router.post("/water-heaters", response_model=WaterHeater, status_code=status.HTTP_201_CREATED)
async def create_water_heater(
    request: CreateWaterHeaterRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Create a new water heater.
    """
    # Convert status and mode strings to enums if provided
    status_enum = WaterHeaterStatus(request.status) if request.status else None
    mode_enum = WaterHeaterMode(request.mode) if request.mode else None
    
    # Create water heater object
    water_heater = WaterHeater(
        id=None,  # Will be generated by the service
        name=request.name,
        model=request.model,
        manufacturer=request.manufacturer,
        target_temperature=request.target_temperature,
        current_temperature=request.current_temperature,
        status=status_enum,
        mode=mode_enum,
        health_status=request.health_status
    )
    
    # Create in repository
    return await service.create_water_heater(water_heater)

@router.patch("/water-heaters/{device_id}/temperature", response_model=WaterHeater)
async def update_temperature(
    device_id: str,
    request: TemperatureUpdateRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Update a water heater's target temperature.
    """
    updated = await service.update_target_temperature(device_id, request.temperature)
    if not updated:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    return updated

@router.patch("/water-heaters/{device_id}/mode", response_model=WaterHeater)
async def update_mode(
    device_id: str,
    request: ModeUpdateRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Update a water heater's operational mode.
    """
    updated = await service.update_mode(device_id, request.mode)
    if not updated:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    return updated

@router.post("/water-heaters/{device_id}/readings", response_model=WaterHeater)
async def add_reading(
    device_id: str,
    request: ReadingAddRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Add a new reading to a water heater.
    """
    updated = await service.add_reading(
        device_id,
        request.temperature,
        request.pressure,
        request.energy_usage,
        request.flow_rate
    )
    if not updated:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    return updated

@router.get("/water-heaters/{device_id}/readings", response_model=List[WaterHeaterReading])
async def get_readings(
    device_id: str,
    limit: int = 24,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Get recent readings for a water heater.
    """
    # Check if device exists
    water_heater = await service.get_water_heater(device_id)
    if not water_heater:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    
    # Get readings
    return await service.get_readings(device_id, limit)

@router.get("/water-heaters/{device_id}/thresholds")
async def check_thresholds(
    device_id: str,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Check if a water heater's current state exceeds any thresholds.
    """
    # Check if device exists
    water_heater = await service.get_water_heater(device_id)
    if not water_heater:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    
    # Check thresholds
    return await service.check_thresholds(device_id)

@router.get("/water-heaters/{device_id}/maintenance")
async def perform_maintenance_check(
    device_id: str,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Perform a maintenance check on a water heater.
    """
    # Check if device exists
    water_heater = await service.get_water_heater(device_id)
    if not water_heater:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Water heater with ID {device_id} not found")
    
    # Perform maintenance check
    return await service.perform_maintenance_check(device_id)

# Health configuration endpoints
@router.get("/water-heaters/health-configuration")
async def get_health_configuration(service: ConfigurableWaterHeaterService = Depends(get_service)):
    """
    Get health configuration for water heaters.
    """
    return await service.repository.get_health_configuration()

@router.post("/water-heaters/health-configuration")
async def set_health_configuration(
    config: Dict[str, Dict[str, Any]],
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Set health configuration for water heaters.
    """
    await service.repository.set_health_configuration(config)
    return await service.repository.get_health_configuration()

# Alert rules endpoints
@router.get("/water-heaters/alert-rules")
async def get_alert_rules(service: ConfigurableWaterHeaterService = Depends(get_service)):
    """
    Get alert rules for water heaters.
    """
    return await service.repository.get_alert_rules()

@router.post("/water-heaters/alert-rules", status_code=status.HTTP_201_CREATED)
async def add_alert_rule(
    rule: AlertRuleRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Add a new alert rule for water heaters.
    """
    rule_dict = rule.model_dump()
    return await service.repository.add_alert_rule(rule_dict)

@router.put("/water-heaters/alert-rules/{rule_id}")
async def update_alert_rule(
    rule_id: str,
    rule: AlertRuleRequest,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Update an existing alert rule.
    """
    rule_dict = rule.model_dump()
    return await service.repository.update_alert_rule(rule_id, rule_dict)

@router.delete("/water-heaters/alert-rules/{rule_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_alert_rule(
    rule_id: str,
    service: ConfigurableWaterHeaterService = Depends(get_service)
):
    """
    Delete an alert rule.
    """
    success = await service.repository.delete_alert_rule(rule_id)
    if not success:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Alert rule with ID {rule_id} not found")
    return None
