repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
        exclude: ^node_modules/
    -   id: detect-private-key
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        exclude: ^(archive/|node_modules/|src/scripts/run_component_failure_prediction_ui\.py)

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

# Flake8 disabled by default - uncomment to run comprehensive code quality checks
# -   repo: https://github.com/pycqa/flake8
#     rev: 6.0.0
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-docstrings]
#         exclude: ^(\.venv.*|node_modules/|archive/|add_.*\.py|examples/|configure_.*\.py|create_clean_db\.py|e2e_.*\.py|scripts/|move_to_archive\.py|run_.*\.py|reset_database\.py|frontend/tests/)
#         args: [--max-line-length=100, "--extend-ignore=D1,D2,D3,D4,E501,E402,F401,E231,E221,F541"]

# Type checking disabled by default - uncomment to run comprehensive type checks
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.3.0
#     hooks:
#     -   id: mypy
#         exclude: ^(archive/|node_modules/)
#         additional_dependencies: [types-requests, types-PyYAML]

# Documentation style checking disabled by default
# -   repo: https://github.com/pycqa/pydocstyle
#     rev: 6.3.0
#     hooks:
#     -   id: pydocstyle
#         exclude: ^(archive/|node_modules/|examples/|scripts/)
#         args: ["--convention=google"]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: ^(add_.*\.py|configure_.*\.py|data_generators/|tests/|archive/|node_modules/|src/scripts/|src/data_generators/|move_to_archive\.py|reset_database\.py|scripts/tdd_workflow\.py)
        args: ["-c", "pyproject.toml", "--confidence-level=high", "--severity-level=high", "--skip=B101,B110,B311", "--quiet"]
        additional_dependencies: ["bandit[toml]"]

# Dependency scanning added as a local hook for better compatibility
-   repo: local
    hooks:
    -   id: safety-check
        name: Safety - Check for security vulnerabilities (report only)
        entry: bash -c 'safety check; exit 0'
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
    -   id: gitleaks

# Test execution is commented out for now to allow other hooks to run
# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: pytest-check
#         entry: python -m pytest -xvs
#         language: system
#         pass_filenames: false
#         always_run: true

# JavaScript and frontend linting/formatting are disabled until Node.js is properly setup
# -   repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v8.40.0
#     hooks:
#     -   id: eslint
#         files: \.(js|jsx)$
#         types: [file]
#         additional_dependencies:
#         -   eslint@8.40.0
#         -   eslint-config-prettier@8.8.0
#         -   eslint-plugin-prettier@4.2.1
#         -   prettier@2.8.8
#
# -   repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v2.8.8
#     hooks:
#     -   id: prettier
#         types_or: [javascript, jsx, css, html]

# Test execution is commented out for now to allow other hooks to run
# -   repo: local
#     hooks:
#     -   id: pytest-tdd
#         name: pytest-tdd
#         entry: python -m pytest src/tests/unit -v --no-header
#         language: system
#         pass_filenames: false
#         always_run: true
