# IoTSphere Development Environment Configuration
# Overrides for the development environment

app:
  environment: "development"
  debug: true
  log_level: "DEBUG"

database:
  type: "sqlite"
  path: "sqlite:///data/iotsphere_dev.db"
  fallback_to_mock: true  # Fall back to mock data if DB is unavailable

services:
  water_heater:
    use_mock_data: false  # Try to use real database first, but fallback allowed
  
  # Development specific monitoring settings
  monitoring:
    use_mock_data: false  # Try to use real database first
    fallback_to_mock: true
    metrics_retention_days: 90  # Keep more data in development environment
    model_health:
      drift_threshold: 0.20   # More permissive drift threshold for development
      accuracy_threshold: 0.80  # More permissive accuracy threshold for development
    
  predictions:
    model_cache_ttl: 300  # Cache prediction models for 5 minutes in development
    enable_development_models: true

security:
  https:
    enabled: false

observability:
  logging:
    format: "text"
    levels:
      api: "DEBUG"
      database: "INFO"
      predictions: "DEBUG"
