apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotsphere-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotsphere-api
  template:
    metadata:
      labels:
        app: iotsphere-api
    spec:
      containers:
      - name: iotsphere-api
        image: iotsphere-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
